services:
  db_test:
    image: postgres:17
    # shm_size: 1g
    container_name: db_test
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      # TS_TUNE_MAX_CONNS: 100
    volumes:
      - ./data:/var/lib/postgresql/data
      # - ./pg_log:/var/lib/postgresql/data/log
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "6433:5432"

  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: orm_test_app
  #   restart: always
  #   depends_on:
  #     - db_test
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 1G
  #   volumes:
  #     - .:/app
  #   working_dir: /app